### PR TITLE
kube-state-metrics doesn't work in recent Kubernetes versions

### LINKED ISSUE #655: kube-state-metrics pod is not working in recent Kubernetes versions
Due to the same API deprecations/changes reported [here](https://www.ibm.com/cloud/blog/announcements/kubernetes-version-1-16-removes-deprecated-apis) , the current ClusterRole defined [here](https://github.com/bitnami/kube-prod-runtime/blob/d34d162c9f91f7eb3b5a73f584d226ad28bd438d/manifests/components/prometheus.jsonnet#L442l) doesn't work anymore in recent Kubernetes versions (e.g 1.16) because pod `kube-state-metrics pod` doesn't get the needed authorizations to poll metrics.

### PR DESCRIPTION
**Pull request by irizzant**
Fix #655 
Due to the same API deprecations/changes reported [here](https://www.ibm.com/cloud/blog/announcements/kubernetes-version-1-16-removes-deprecated-apis) , the current ClusterRole defined [here](https://github.com/bitnami/kube-prod-runtime/blob/d34d162c9f91f7eb3b5a73f584d226ad28bd438d/manifests/components/prometheus.jsonnet#L442l) doesn't work anymore in recent Kubernetes versions (e.g 1.16) because pod `kube-state-metrics pod` doesn't get the needed authorizations to poll metrics.

### CODE REVIEW

**Comment by sameersbn** [comment]
Thanks for the contributions. Looks like this update requires some more changes as the monitoring tests are currently failing. 

You can execute the monitoring tests by executing the the following command:

```
ginkgo -v --focus=Monitoring /path/to/kube-prod-runtime/tests/ -- --kubeconfig /path/to/.kubecfg --dns-suffix ${dnsZone}
```

**Comment by irizzant** [comment]
@sameersbn Sorry but I need some help here.
I'm not a go developer so I don't know how to run the command you provided.

**Comment by irizzant** [comment]
@sameersbn Sorry, I see the checks are still pending. Is there any way to see if the checks run successfully now?

**Comment by sameersbn** [comment]
@irizzant were you able to install BKPR to your cluster with these changes. If yes, did it work as expected?

**Comment by irizzant** [comment]
@sameersbn as I said I'm not a Go developer but I managed to generate Kubernetes manifests with `kubecfg` and run them in minikube and they work as expected

**Comment by sameersbn** [comment]
@irizzant kube-state-metrics has been updated to the latest version and the configuration has been updated. Please try out the master on the k8s 1.16 cluster and let me know if you experience any issues.

Sorry about the delay in handling your request :pray:

**Comment by irizzant** [comment]
@sameersbn thank you for the fix, I've just tried it and it works now

**Pull request closed without merging**
