### PR TITLE
[maintenance/master] Update all images with newer OpenSSL 1.1.1d-0+deb10u3

### PR DESCRIPTION
**Pull request by javsalgar**
Update all bitnami images based on Debian 10 with the latest release. I will close all the automatic component PRs so everything is tested once.

### CODE REVIEW

**Comment by dbarranco** [comment]
lgtm

**Comment by javsalgar** [comment]
bors merge

**Comment by javsalgar** [comment]
bors try

**Comment by javsalgar** [comment]
bors merge

**Comment by jjo** [comment]
bors try

**Comment by javsalgar** [comment]
bors merge

**Pull request merged**
