### PR TITLE
Add EKS to jsonnet unittest

### PR DESCRIPTION
**Pull request by anguslees**

### CODE REVIEW

**Comment by falfaro** [comment]
This is missing changes to Jenkisfile, right? Like those from commit ec5270f59bf7d22805a95766c430d3c52affb26f ?

**Comment by anguslees** [comment]
> This is missing changes to Jenkisfile, right?

Correct, this is _just_ what's needed to include the EKS manifests in `make -C manifests validate` (run by Jenkinsfile `manifests` stage)

I'm ok holding off on this part if we want to wait until the EKS `kubeprod install` tests are also added to Jenkinsfile, although the two are independent.

**Comment by anguslees** [comment]
bors r=falfaro

**Comment by anguslees** [comment]
Aha, broken by a change in e27db05f.  Updated.

**Comment by anguslees** [comment]
bors r=falfaro

**Pull request merged**
