### PR TITLE
[jjo] release-1.7: Merge #952 from master branch

### PR DESCRIPTION
**Pull request by jjo**

### CODE REVIEW

**Review by jbianquetti-nami — APPROVED** [review]

**Comment by dbarranco** [comment]
bors merge

**Comment by dbarranco** [comment]
bors try

**Review by dbarranco — APPROVED** [review]

**Comment by dbarranco** [comment]
AWS limits, crap

**Comment by dbarranco** [comment]
bors try

**Comment by dbarranco** [comment]
bors try

**Comment by jjo** [comment]
bors merge

**Comment by jjo** [comment]
bors retry

**Pull request merged**
