### PR TITLE
[maintenance/release-1.5] Update all images with newer OpenSSL 1.1.1d-0+deb10u3

### PR DESCRIPTION
**Pull request by javsalgar**

### CODE REVIEW

**Comment by javsalgar** [comment]
bors merge

**Comment by javsalgar** [comment]
bors merge

**Comment by javsalgar** [comment]
bors try

**Comment by javsalgar** [comment]
bors merge

**Comment by javsalgar** [comment]
bors merge

**Comment by jjo** [comment]
bors try

**Comment by javsalgar** [comment]
bors merge

**Pull request merged**
